"""Render and persist model definitions from the admin console.

Two modes, because they trade off differently (see docs/DEPLOYMENT.md):

  * **preview** - render the YAML and hand it back. The admin commits it to git,
    so the registry keeps its review trail and rollback story.
  * **write**   - write it straight into config/models/. Faster, but the file now
    lives only on that host unless someone copies it back into the repo.

Both go through the same validation, so nothing reaches disk that the registry
loader would later reject.
"""

from __future__ import annotations

import logging
import os
import tempfile
from pathlib import Path
from typing import Any

import yaml
from pydantic import ValidationError

from app.core.errors import ErrorCode, GatewayError
from app.registry.schema import ModelDefinition

log = logging.getLogger(__name__)

# Field order that reads top-down like the PRD describes a model.
_SPEC_ORDER = [
    "upstream_model",
    "purpose",
    "limits",
    "modalities",
    "capabilities",
    "protocols",
    "agent_clients",
    "vision_policy",
    "endpoints",
    "enabled",
]


class _OrderedDumper(yaml.SafeDumper):
    """Keep insertion order and indent lists under their key."""

    def increase_indent(self, flow=False, indentless=False):  # noqa: ANN001
        return super().increase_indent(flow, False)


def _clean(value: Any) -> Any:
    """Drop nulls so the rendered file has no `key: null` noise."""
    if isinstance(value, dict):
        return {k: _clean(v) for k, v in value.items() if v is not None}
    if isinstance(value, list):
        return [_clean(v) for v in value]
    return value


def validate_definition(payload: dict[str, Any]) -> ModelDefinition:
    """Parse and check a definition, turning schema errors into 400s."""
    try:
        return ModelDefinition.model_validate(payload)
    except ValidationError as exc:
        problems = [
            {
                "field": ".".join(str(p) for p in err["loc"]),
                "message": err["msg"],
            }
            for err in exc.errors()[:12]
        ]
        raise GatewayError(
            ErrorCode.INVALID_REQUEST,
            "The model definition is not valid.",
            details={"problems": problems},
        ) from exc
    except ValueError as exc:
        raise GatewayError(
            ErrorCode.INVALID_REQUEST, f"The model definition is not valid: {exc}"
        ) from exc


def render_yaml(definition: ModelDefinition) -> str:
    """Canonical YAML for a validated definition."""
    data = _clean(definition.model_dump(mode="json", exclude_none=True))
    spec = data.get("spec", {})
    data["spec"] = {k: spec[k] for k in _SPEC_ORDER if k in spec} | {
        k: v for k, v in spec.items() if k not in _SPEC_ORDER
    }
    body = yaml.dump(
        data,
        Dumper=_OrderedDumper,
        sort_keys=False,
        allow_unicode=True,
        default_flow_style=False,
        width=88,
    )
    return (
        "# Generated by the LiteGate admin console.\n"
        "# Capabilities should reflect what the backend was measured to do,\n"
        "# not what the model name suggests (PRD 9.5).\n"
        f"{body}"
    )


def model_path(config_dir: Path, alias: str) -> Path:
    """Resolve <config>/models/<alias>.yaml, refusing anything that escapes it.

    The alias pattern already forbids slashes and a leading dot, but the
    containment check is kept so a future schema relaxation cannot silently turn
    into an arbitrary-file write.
    """
    models_dir = (config_dir / "models").resolve()
    candidate = (models_dir / f"{alias}.yaml").resolve()
    if candidate.parent != models_dir:
        raise GatewayError(
            ErrorCode.INVALID_REQUEST, f"Refusing to write outside the registry: {alias!r}"
        )
    return candidate


def write_model(config_dir: Path, definition: ModelDefinition) -> Path:
    """Atomically write the definition into the registry.

    Written to a temp file in the same directory and renamed, so a reload that
    lands mid-write can never observe a half-written file.
    """
    path = model_path(config_dir, definition.alias)
    path.parent.mkdir(parents=True, exist_ok=True)
    content = render_yaml(definition)

    try:
        fd, tmp_name = tempfile.mkstemp(
            dir=str(path.parent), prefix=f".{definition.alias}.", suffix=".tmp"
        )
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as handle:
                handle.write(content)
                handle.flush()
                os.fsync(handle.fileno())
            # mkstemp creates 0600. A registry file holds no secrets - api_key_env
            # is the name of an env var, never its value - and should look like a
            # file a human committed, so match the usual 0644.
            os.chmod(tmp_name, 0o644)
            os.replace(tmp_name, path)
        except Exception:
            try:
                os.unlink(tmp_name)
            except OSError:
                pass
            raise
    except PermissionError as exc:
        raise GatewayError(
            ErrorCode.INVALID_REQUEST,
            "The registry directory is not writable, so the model cannot be saved "
            "from the console. This is expected when config/ is mounted read-only "
            "(the hardened Docker default). Use Preview YAML and commit the file "
            "to git instead.",
            details={"path": str(path.parent)},
        ) from exc
    except OSError as exc:
        raise GatewayError(
            ErrorCode.INTERNAL_ERROR, f"Could not write the model file: {exc}"
        ) from exc

    log.info("wrote model definition %s", path)
    return path


def delete_model(config_dir: Path, alias: str) -> bool:
    path = model_path(config_dir, alias)
    if not path.exists():
        return False
    try:
        path.unlink()
    except PermissionError as exc:
        raise GatewayError(
            ErrorCode.INVALID_REQUEST,
            "The registry directory is not writable, so the model cannot be removed "
            "from the console. Delete the file and redeploy instead.",
            details={"path": str(path)},
        ) from exc
    log.info("deleted model definition %s", path)
    return True


def registry_writable(config_dir: Path) -> bool:
    """Whether the console may offer 'save to disk' at all."""
    models_dir = config_dir / "models"
    try:
        return models_dir.is_dir() and os.access(models_dir, os.W_OK)
    except OSError:
        return False
